import type { Metadata } from "next";
import { Orienta, Comme } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/global/Footer";
import Providers from "./providers";

const orienta = Orienta({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-orienta',
  display: 'swap',
});

const comme = Comme({
  subsets: ['latin'],
  variable: '--font-comme',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orienta.variable} ${comme.variable} font-sans antialiased mt-[45px]`}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
